import React, { useEffect, useState } from 'react'
import { FlatList, Keyboard, Text, TextInput, TouchableOpacity, View } from 'react-native'
import styles from './styles';
import axios from "axios";
//import Tabletop from "tabletop";
import Papa from 'papaparse';
import { signOut } from 'firebase/auth'
import { collection, query, where, doc, getDoc, getDocs, addDoc, onSnapshot, setDoc } from 'firebase/firestore';
import { db, auth } from '../../firebase/config'
import { useNavigation } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack'

const Stack = createStackNavigator();

export default function HomeScreen(props) {
    const [entityTextAdd, setEntityTextAdd] = useState('')
    const [entityTextLeave, setEntityTextLeave] = useState('')
    const [entities, setEntities] = useState([])
    const [sheetData, setSheetData] = useState([])

    // Populate entityRef (houses collection reference for house entities with matching houseIDs)
    const userID = props.extraData.id
    const userEmail = props.extraData.email
    const userName = props.extraData.fullName

    const userRef = doc(db, 'users', `${userID}`)
    const colRef = collection(db, 'users', `${userID}`, 'houseIDs')
    

    const navigation = useNavigation()

    const fetchData = () => {
        // GET request sent to webhook.site using unique token generated by webhook.site 
        //fetch('http://webhook.site/token/007347fc-f34d-4286-88d8-a10bbb8b2292/request/latest')
        axios
            .get('http://webhook.site/token/007347fc-f34d-4286-88d8-a10bbb8b2292/request/latest')
            .then((response) => {
                console.log("in fetchData: ", response.data.content)
                // How to return json object from here?
            })
            .catch((error) => console.error(error))    
    }

    useEffect(() => {
        console.log("in useEffect HomeScreen")
        console.log("About to find google sheet")

        // setInterval calls getSheetData every 300000 milliseconds (every 5 minutes)
        var data = fetchData();
        //var json = JSON.parse(data);
        console.log("data: ", data)
        //update = setInterval(fetchData, 30000)

        getDoc(userRef)
        .then((docSnap) => {
            console.log("user's full name: ", docSnap.data().fullName)
        })
        
        onSnapshot(colRef, (snapshot) => {
            let newEntities = []
            snapshot.forEach(async (document) => { // For each houseID that a user has
                
                // Get the doc from houses that match the current houseID we have using a query and getDocs
                const docRef = doc(db, 'houses', `${document.data().houseID}`)
                const docSnap = await getDoc(docRef)
                if(docSnap.exists()) {
                    let entity = docSnap.data()
                    entity.id = doc.id
                    newEntities.push(entity)
                } 
                else {
                    alert("House doesn't exist")
                } 
            })
            console.log("newEntitites: ", newEntities)
            setEntities(newEntities)
        });
    }, [])

    const onAddButtonPress = () => {
        // Adding a new house
        if(entityTextAdd && entityTextAdd.length > 0) {
            const houseRef = query(collection(db, 'houses'), where('houseID', '==', `${entityTextAdd}`))
            console.log(houseRef)
            if(houseRef) { // If the house reference exists, set the user doc to have the houseID
                const data = {
                    houseID: entityTextAdd
                }
                const houseIDsDocRef = doc(db, 'users', `${userID}`, 'houseIDs', `${entityTextAdd}`)
                setDoc(houseIDsDocRef, data)
                    .then(_doc => {
                        setEntityTextAdd('')
                        Keyboard.dismiss()
                        alert("Joined existing house")
                    })
                    .catch((error) => {
                        alert(error)
                    });
            }
            else {
                alert("No existing house")
            }
        }

        /*
        // Adding an entrance 
        if (entityText && entityText.length > 0) {
            const data = {
                title: entityText,
                ownerID: userID,
                openBool: false
            };
            addDoc(entityRef, data)
                .then(_doc => {
                    setEntityText('')
                    Keyboard.dismiss()
                })
                .catch((error) => {
                    alert(error)
                });
        } */
    }

    const onLeaveButtonPress = () => {
        /*if (entityTextLeave && entityTextLeave.length > 0) {
            const data = {
                title: entityText,
                ownerID: userID,
                openBool: false
            };
            addDoc(entityRef, data)
                .then(_doc => {
                    setEntityText('')
                    Keyboard.dismiss()
                })
                .catch((error) => {
                    alert(error)
                });
        }*/
        console.log("Implement")
    }

    const onChatButtonPress = () => {
        return( // Creating a new stack navigator
            navigation.navigate('Chat')
        )
    }

    const onLogoutButtonPress = () => {
        signOut(auth)
            .then(() => {
                alert("You have been logged out")
            })
            .catch((err) => {
                console.log(err)
            })
    }

    const renderEntity = ({item, index}) => {
        return (
            <View style={styles.entityContainer}>
                <Text style={styles.entityTextAdd}>
                    {index+1}. {"\t"} {item.name} {"\n"} HouseID: {item.houseID}
                </Text>
            </View>
        )
    }

    return (
        <View style={styles.container}>
            <TouchableOpacity style={styles.button} onPress={onLogoutButtonPress}>
                <Text style={styles.buttonText}>Logout</Text>
            </TouchableOpacity>
            
            <TouchableOpacity style={styles.button} onPress={onChatButtonPress}>
                <Text style={styles.buttonText}>Chat</Text>
            </TouchableOpacity>

            <View style={styles.formContainer}>
                <TextInput
                    style={styles.input}
                    placeholder='Join/create a new house'
                    placeholderTextColor="#aaaaaa"
                    onChangeText={(text) => setEntityTextAdd(text)}
                    value={entityTextAdd}
                    underlineColorAndroid="transparent"
                    autoCapitalize="none"
                />
                <TouchableOpacity style={styles.button} onPress={onAddButtonPress}>
                    <Text style={styles.buttonText}>Add</Text>
                </TouchableOpacity>
            </View>

            <View style={styles.formContainer}>
                <TextInput
                    style={styles.input}
                    placeholder='Leave a house'
                    placeholderTextColor="#aaaaaa"
                    onChangeText={(text) => setEntityTextLeave(text)}
                    value={entityTextLeave}
                    underlineColorAndroid="transparent"
                    autoCapitalize="none"
                />
                <TouchableOpacity style={styles.button} onPress={onLeaveButtonPress}>
                    <Text style={styles.buttonText}>Leave</Text>
                </TouchableOpacity>
            </View>
            { entities && (
                <View style={styles.listContainer}>
                    <FlatList
                        data={entities}
                        renderItem={renderEntity}
                        keyExtractor={(item) => item.id}
                        removeClippedSubviews={true}
                    />
                </View>
            )}
        </View>
    )
}